Wsei.ExchangeThings.Web/Entities/ItemEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.ExchangeThings.Web.Entities
{
    public class ItemEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsVisible { get; set; }

        public override string ToString()
        {
            return $"Name : {Name}, Description : {Description}, Visibility: {IsVisible}";
        }
    }
}

Wsei.ExchangeThings.Web/Entities/ProductsEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Wsei.ExchangeThings.Web.Entities
{
    public class ProductsEntity
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Wsei.ExchangeThings.Web/Models/AddNewItemConfirmationViewModel.cs
namespace Wsei.ExchangeThings.Web.Models
{
    public class AddNewItemConfirmationViewModel
    {
        public int Id { get; internal set; }

        public string Name { get; internal set; }
    }
}

Wsei.ExchangeThings.Web/Models/AddNewItemResponseModel.cs
namespace Wsei.ExchangeThings.Web.Controllers
{
    public class AddNewItemResponseModel<T>
    {
        public bool success { get; set; }
        public string message { get; set; }
        public T data { get; set; }
    }
}

Wsei.ExchangeThings.Web/Models/ErrorViewModel.cs
using System;

namespace Wsei.ExchangeThings.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Wsei.ExchangeThings.Web/Models/ItemModel.cs
namespace Wsei.ExchangeThings.Web.Models
{
    public class ItemModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public bool IsVisible { get; set; }
    }
}

Wsei.ExchangeThings.Web/Controllers/ExchangesController.cs
using Microsoft.AspNetCore.Mvc;
using Wsei.ExchangeThings.Web.Database;
using Wsei.ExchangeThings.Web.Entities;
using Wsei.ExchangeThings.Web.Filters;
using Wsei.ExchangeThings.Web.Models;

namespace Wsei.ExchangeThings.Web.Controllers
{
    public class ExchangesController : Controller
    {
        private readonly ExchangesDbContext _dbContext;

        public ExchangesController(ExchangesDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [ServiceFilter(typeof(MyCustomActionFilter))]
        public IActionResult Show(string id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(ItemModel item)
        {
            var entity = new ItemEntity
            {
                Name = item.Name,
                Description = item.Description,
                IsVisible = item.IsVisible
            };

            _dbContext.Items.Add(entity);
            _dbContext.SaveChanges();

            return RedirectToAction("AddConfirmation");
        }

        [HttpGet]
        public IActionResult AddConfirmation()
        {
            return View();
        }
    }
}

Wsei.ExchangeThings.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Wsei.ExchangeThings.Web.Models;

namespace Wsei.ExchangeThings.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Wsei.ExchangeThings.Web/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Wsei.ExchangeThings.Web.Database;
using Wsei.ExchangeThings.Web.Entities;
using Wsei.ExchangeThings.Web.Models;

namespace Wsei.ExchangeThings.Web.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class ItemController : ControllerBase
    {
        private readonly ExchangesDbContext _dbContext;

        public ItemController(ExchangesDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public AddNewItemResponseModel<DbSet<ItemEntity>> Post(ItemModel item) {
            bool isValid = !string.IsNullOrEmpty(item.Description) && !string.IsNullOrEmpty(item.Name);
            string message = isValid ? "" : "Input fields cannot be empty";

            if(isValid)
            {
                var entity = new ItemEntity
                {
                    Name = item.Name,
                    Description = item.Description,
                    IsVisible = item.IsVisible
                };

                _dbContext.Items.Add(entity);
                _dbContext.SaveChanges();
            }

            var res = new AddNewItemResponseModel<DbSet<ItemEntity>>
            {
                success = isValid,
                message = message,
                data = isValid ? _dbContext.Items : null
            };

            return res;
        }
    }
}

Wsei.ExchangeThings.Web/Views/Exchanges/Add.cshtml
@model ItemModel

<h2>Add new item</h2>

<div id="success-alert" class="alert alert-success" style="display: none">
    Item added
    successfully
</div>
<div id="error-alert" class="alert alert-danger" style="display: none">
    Cannot add item : <div id="msg"></div>
</div>

<form method="POST">
    <div class="form-group">
        <label asp-for="Name">Item name</label>
        <input asp-for="Name" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Description">Description</label>
        <input asp-for="Description" class="form-control" />
    </div>

    <div class="form-check">
        <input asp-for="IsVisible" class="form-check-input" />
        <label asp-for="IsVisible" class="form-check-label">Item visible?</label>
    </div>

    <div class="form-group">
        <input type="submit" value="Add new item" />
    </div>
</form>
<div id="list" style="display: none">
</div>
@section Scripts {
    <script src="~/js/addNewItem.js"></script>
    <style>
        table {
            border-collapse: collapse;
            text-align: center;
        }
    </style>
}

Wsei.ExchangeThings.Web/Views/Exchanges/AddConfirmation.cshtml
@model AddNewItemConfirmationViewModel
@inject Wsei.ExchangeThings.Web.Database.ExchangesDbContext DbContext;

<h2>Add new item</h2>

<p>Congratulations!</p>

<p>Your new item was successfully added to the system</p>

<table style="width:100%">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Visibility</th>
    </tr>
    @foreach (var item in DbContext.Items)
    {
    <tr>
        <td>@item.Id</td>
        <td>@item.Name</td>
        <td>@item.Description</td>
        <td>@item.IsVisible</td>
    </tr>
    }
</table>

Wsei.ExchangeThings.Web/Views/Exchanges/Show.cshtml
<h2>Hi man, this is my new app</h2>

Wsei.ExchangeThings.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<vc:latest-item />
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Wsei.ExchangeThings.Web/Views/Shared/Components/LatestItem/Index.cshtml
@model Wsei.ExchangeThings.Web.Entities.ItemEntity
@if (Model != null)
{
    <div>Latest item added: @Model.ToString()</div>
}

Wsei.ExchangeThings.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Wsei.ExchangeThings.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Wsei.ExchangeThings.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exchanges" asp-action="Add">Add new item</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Wsei.ExchangeThings.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>